using System.Collections;
using System.Collections.Generic;
using UnityEngine;
//富妾骇Pw代刚
public class gunController : MonoBehaviour
{

    public GameObject fire;
    public GameObject bullet; // luㄓ方 (bUnityざ堡ぉ欷J)
    public GameObject Firepoint; // og把σI (bUnityざ堡ぉ欷J)
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Q))
        {
            // 狡slu斓og把σIW
            Instantiate(bullet, Firepoint.transform.position, transform.rotation);
        }
        if (Input.GetKeyDown(KeyCode.E))
        {
            // 狡slu斓og把σIW
            Instantiate(fire, Firepoint.transform.position, transform.rotation);

        }
    }
}
